# SPDX-License-Identifier: Apache-2.0
---
# DCI metadata detection tasks for redhatci.ocp.test_report_send

- name: Set is_ci attribute
  ansible.builtin.set_fact:
    rmg_ci_runtime: "{{ rmg_ci_runtime | combine({'is_ci': true}) }}"
  when:
    - lookup("env","CI") | lower == "true"
    - lookup('env', 'DCI_CS_URL') | length > 0

- name: Update rmg_ci_runtime.type for {{ rmg_ci_system }}
  ansible.builtin.set_fact:
    ci: "{{ ci | default({}) | combine({'type': rmg_ci_system}) }}"

- name: Update ci.url for {{ rmg_ci_system }}
  ansible.builtin.set_fact:
    ci: "{{ ci | combine({'url': lookup('env', 'DCI_CS_URL')}) }}"

- name: Print rmg_meta_data (Before squash of metadata key)
  ansible.builtin.debug:
    var: rmg_meta_data

- name: Update ci in rmg_ci_runtime
  ansible.builtin.set_fact:
    rmg_ci_runtime: "{{ rmg_ci_runtime | combine({'ci': ci}) }}"


- name: Merge optional "metadata" attribute under root rmg_meta_data
  ansible.builtin.set_fact:
    rmg_meta_data: "{{ rmg_meta_data | combine(rmg_meta_data.metadata | default({})) }}"
  when:
    - rmg_meta_data | length > 0
    - ("metadata" in rmg_meta_data.keys())
    - rmg_meta_data.metadata | length > 0

- name: Print rmg_meta_data (AFTER merging optional metadata attribute)
  ansible.builtin.debug:
    var: rmg_meta_data

- name: Delete rmg_meta_data key "metadata"
  ansible.builtin.set_fact:
    rmg_meta_data: "{{ rmg_meta_data | combine({'metadata': omit}) }}"
  when:
    - rmg_meta_data | length > 0
    - ("metadata" in rmg_meta_data.keys())
    - rmg_meta_data.metadata | length > 0

- name: Print rmg_meta_data (AFTER deleting of metadata key)
  ansible.builtin.debug:
    var: rmg_meta_data

- name: combine rmg_ci_runtime and rmg_meta_data
  ansible.builtin.set_fact:
    rmg_meta_data: "{{ rmg_meta_data | combine(rmg_ci_runtime) }}"

- name: Print rmg_meta_data (AFTER combining with rmg_ci_runtime)
  ansible.builtin.debug:
    var: rmg_meta_data

