# SPDX-License-Identifier: Apache-2.0
---
# tasks file main.yml for role junit2json

- name: Validate role variables
  ansible.builtin.assert:
    that:
      - junit2_input_reports_list | length > 0
      - junit2_output_dir | length > 0
    fail_msg: "One of the mandatory variables is missing or empty"

# During repeating tests, this variable needs to be reset each run
- name: Initialize reports variable
  ansible.builtin.set_fact:
    junit2_reports_list: []

- name: Print input reports variable
  ansible.builtin.debug:
    var: junit2_input_reports_list
    verbosity: 2
