# SPDX-License-Identifier: Apache-2.0
---
# tasks file for redhatci.ocp.report_combine

- name: Validate the file exists, readable and non-empty
  ansible.builtin.include_tasks:
    file: "validate-file.yml"
  vars:
    _rc_file_path: "{{ _rc_file_item.path }}"

- name: Read JSON file {{ _rc_file_item.path }}
  ansible.builtin.slurp:
    src: "{{ _rc_file_item.path }}"
  register: _rc_file_read

- name: Parse data as JSON from file {{ _rc_file_item.path }}
  ansible.builtin.set_fact:
    "{{ _rc_file_item.name }}": "{{ _rc_file_read.content | b64decode | from_json | default({}) }}"

- name: "Verify the data is not empty (mandatory={{ _rc_file_item.mandatory | default(false) | str}})"
  ansible.builtin.assert:
    that:
      - vars[_rc_file_item.name] | default({}) | length > 0
    fail_msg: >
      The role (report_combine) does not support combining empty data
        in: {{ _rc_file_item.name }}
        from: {{ _rc_file_item.path }}
  when:
    - _rc_file_item.mandatory is defined
    - _rc_file_item.mandatory | default(false)

- name: Print user note
  ansible.builtin.debug:
    msg: "NOTE: this run of the role has an empty data in {{_rc_file_item.path}}"
  when:
    - not (_rc_file_item.mandatory | default(false)
    - vars[_rc_file_item.name] | length == 0

- name: "Print {{ _rc_file_item.name }} (vebosity>=3)"
  ansible.builtin.debug:
    msg: "{{ _rc_file_item.name }}: {{ vars[_rc_file_item.name] }}"
    verbosity: 3
