# SPDX-License-Identifier: Apache-2.0
---
# meta file for redhatci.ocp.report_combine

galaxy_info:
  author: Red Hat CI
  description: Role to combine test reports and metadata into event structures for collectors
  company: Red Hat
  license: Apache-2.0
  min_ansible_version: "2.14"
  platforms:
    - name: EL
      versions:
        - "8"
        - "9"
    - name: Fedora
      versions:
        - "37"
        - "38"
        - "39"
  galaxy_tags:
    - testing
    - reporting
    - splunk
    - ci
    - metadata
    - combine

dependencies: []
