---
- name: Test activities before main report processing
  hosts: localhost
  connection: local
  tasks:
    - name: Do some pre-test activities
      ansible.builtin.debug:
        msg: "Do some pre-test activities"

- name: Import main report send playbook
  import_playbook: report_send.yml
