name: ansible-lint
on:
  pull_request:
    branches:
      - "*"
jobs:
  build:
    name: Ansible Lint
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install ansible-lint
        # Install ansible-lint from same branch as GHA
        run: >
          pip install ansible-lint==25.8.2

      - name: Install requirements for plugins
        run: >
          pip install \
            ansible \
            jira \
            jmespath \
            jsonpatch \
            junitparser \
            kubernetes \
            ncclient \
            netaddr
      - name: Run ansible-lint
        run: ansible-lint -v
