---
name: ci/github
on:
  pull_request:
    branches:
      - "*"
jobs:
  ansible-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v5
      - name: Run ansible-lint
        uses: ansible/ansible-lint@v25
